const GENRES: { readonly [key: string]: string } = {
  "0": "Acoustic",
  "1": "Alternative",
  "2": "Ambient",
  "3": "Anime",
  "4": "Blues",
  "5": "Bossanova",
  "6": "Classical",
  "7": "Country",
  "8": "Dance",
  "9": "Disco",
  "10": "Electronic",
  "11": "EDM",
  "12": "Emo",
  "13": "Folk",
  "14": "Funk",
  "15": "Garage",
  "16": "Gospel",
  "17": "Hip-hop",
  "18": "House",
  "19": "Industrial",
  "20": "Jazz",
  "21": "K-pop",
  "22": "Latin",
  "23": "Metal",
  "24": "New Age",
  "25": "New Release",
  "26": "Piano",
  "27": "Pop",
  "28": "Punk",
  "29": "R&B",
  "30": "Rock",
  "31": "Singer-songwriter",
  "32": "Soundtracks",
  "33": "Techno",
  "34": "Indie",
} as const;

export default GENRES;
